
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  ENVIRONMENT:
    Type: String
    Default: dev
  PROJECT:
    Type: String
  DOMAIN:
    Type: String
  BASEPATH:
    Type: String
    Default: node-version

Resources:
  # Api Gateway
  ApiDeployment:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${PROJECT}-${ENVIRONMENT}
      StageName: !Ref ENVIRONMENT
      Cors:
        AllowMethods: "'GET, OPTIONS'"
        AllowHeaders: "'Accept,Content-Type'"
        AllowOrigin: "'*'"
  BasePath:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref BASEPATH
      DomainName: !Ref DOMAIN
      RestApiId: !Ref ApiDeployment
      Stage: !Ref ApiDeployment.Stage

  # node10.x
  Version10Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${PROJECT}-10-${ENVIRONMENT}
      CodeUri: ./dist/src/
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 5
      Events:
        HttpReqs:
          Type: Api
          Properties:
            RestApiId: !Ref ApiDeployment
            Path: /10
            Method: GET

  Version10LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Version10Lambda}
      RetentionInDays: 30

  # node12.x
  Version12Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${PROJECT}-12-${ENVIRONMENT}
      CodeUri: ./dist/src/
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 5
      Events:
        HttpReqs:
          Type: Api
          Properties:
            RestApiId: !Ref ApiDeployment
            Path: /12
            Method: GET

  Version12LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Version12Lambda}
      RetentionInDays: 30

  # node14.x
  Version14Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${PROJECT}-14-${ENVIRONMENT}
      CodeUri: ./dist/src/
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 5
      Events:
        HttpReqs:
          Type: Api
          Properties:
            RestApiId: !Ref ApiDeployment
            Path: /14
            Method: GET

  Version14LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Version14Lambda}
      RetentionInDays: 30
