  
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 5