
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  ENVIRONMENT:
    Type: String
    Default: dev
  PROJECT:
    Type: String
  DOMAIN:
    Type: String
  BASEPATH:
    Type: String
    Default: node10-version

Resources:
  VersionLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${PROJECT}-${ENVIRONMENT}
      CodeUri: ./dist/src/
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 5
      Events:
        HttpReqs:
          Type: Api
          Properties:
            RestApiId: !Ref ApiDeployment
            Path: /
            Method: GET

  VersionLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${VersionLambda}
      RetentionInDays: 90

  # Api Gateway
  ApiDeployment:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${PROJECT}-${ENVIRONMENT}
      StageName: !Ref ENVIRONMENT
      Cors:
        AllowMethods: "'GET, OPTIONS'"
        AllowHeaders: "'Accept,Content-Type'"
        AllowOrigin: "'*'"

  BasePath:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref BASEPATH
      DomainName: !Ref DOMAIN
      RestApiId: !Ref ApiDeployment
      Stage: !Ref ApiDeployment.Stage
