
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  ENVIRONMENT:
    Type: String
    Default: dev
  PROJECT:
    Type: String
  DOMAIN_NAME:
    Type: String
  BASE_PATH:
    Type: String
    Default: node10

Resources:
  VersionLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${PROJECT}-${ENVIRONMENT}
      CodeUri: ./dist/src/
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 5
      Events:
        HttpReqs:
          Type: Api
          Properties:
            RestApiId: !Ref ApiDeployment
            Path: /
            Method: GET

  # Api Gateway
  ApiDeployment:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${PROJECT}-${ENVIRONMENT}
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET, OPTIONS'"
        AllowHeaders: "'Accept,Content-Type'"
        AllowOrigin: "'*'"

  BasePath:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref BASE_PATH
      DomainName: !Ref DOMAIN_NAME
      RestApiId: !Ref ApiDeployment
      Stage: !Ref ApiDeployment.Stage
